### ISSUE TITLE
this is not where you store everything

### ISSUE THREAD

**Issue by raymond-1227** [Quinxxxx/Discord-themes#1]
this is open source platform not your onedrive solution

**Comment by mudrhiod** [comment]
mb sir... u will be my onedrive solution now

**Comment by raymond-1227** [comment]
no and get a life use google drive

**Comment by flandolf** [comment]
bro use nextcloud

**Comment by raymond-1227** [comment]
you literally use oracle cloud always free tier and that's in risk of being terminated from using oracle's service

**Comment by flandolf** [comment]
ok ....... u also use oracle free tier bozo

**Comment by raymond-1227** [comment]
the fact i don't use the thing i set up

**Comment by mudrhiod** [comment]
thnx for the convo about my onedrive solution issues guys!!

**Comment by raymond-1227** [comment]
ok
