### ISSUE TITLE
why you store things here

### ISSUE THREAD

**Issue by matejmajny** [Quinxxxx/Discord-themes#2]
that doesn't make sense really

**Comment by matejmajny** [comment]
or it's open-sourcing your themes????

**Comment by mudrhiod** [comment]
theyre open source regardless

**Comment by mudrhiod** [comment]
> that doesn't make sense really

<:husk:950479558208004186>

**Comment by matejmajny** [comment]
> theyre open source regardless

so you're developer

**Comment by mudrhiod** [comment]
no

**Comment by matejmajny** [comment]
> no

How no that doesnt make sense you literally use Github?????

**Comment by mudrhiod** [comment]
ok mb sir...

**Comment by matejmajny** [comment]
ok sure closed with comment
